#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

LATEST_RESULTS=$(curl -sSL -u "$user:$password" "$url/api/versions/$path")

if echo $LATEST_RESULTS | jq -e 'has("errors")' > /dev/null; then
	echo $LATEST_RESULTS | jq -c '.errors[0]'
	echo "[]" >&3
else 
	echo $LATEST_RESULTS | jq -c '[{version: .version}]' >&3
fi
