#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>"
  exit 1
fi

source $(dirname $0)/common.sh

cd $destination

version=$(jq -r '.version.version // ""' < $request_payload)
if [ -z "$version" ]; then
	echo "invalid request (missing version)"
	exit 1
fi

explode=$(jq -r '.params.explode // "false"' < $request_payload)

pattern=$(echo $regexp | sed -e 's/(.*)/*/')
results=$(jfrog rt dl $path/$pattern --props="version=$version" --recursive=false --flat=true $jfrog_args)

if ! echo "$results" | grep -q "Downloaded 1 artifact"; then
	echo "Failed to get any artifacts:"
	echo $results
	exit 1
fi

filename=$(echo $regexp | sed -e 's/(.*)/'"$version"'/')
if [ "$explode" = "true" ]; then
	tar -xvf $filename
	rm $filename
fi

echo '{"version": { "version": "'$version'"}, "metadata": []}' >&3





